updated version to 1.9.1

diff --git a/Unix/configure b/Unix/configure
--- a/Unix/configure
+++ b/Unix/configure
@@ -40,12 +40,12 @@ if [ -n "$OMI_BUILDVERSION_MAJOR" -a -n "$OMI_BUILDVERSION_MINOR" -a -n "$OMI_BU
     revision=$OMI_BUILDVERSION_PATCH
     patch_level=$OMI_BUILDVERSION_BUILDNR
 else
-    echo "*** UNABLE TO LOCATE FILE omi.version; USING VERSION 1.7.0.0 ***" >& 2
+    echo "*** UNABLE TO LOCATE FILE omi.version; USING VERSION 1.9.1.0 ***" >& 2
     echo "*** Update build process to include omi.version from superproject! ***" >& 2
 
     major=1
     minor=9
-    revision=0
+    revision=1
     patch_level=0
 fi
 
